### ISSUE TITLE
A few safety and usage issues

### ISSUE THREAD

**Issue by SleepiCaffeine** [jeffstevens98/adventOfCode2023#1]
# Personal Message:
Heya, I was scrolling through Reddit and saw your submission for day 1. I really like the way you approached it, its surprisingly simple and easy to understand!
Having said that, I did notice some issues in your code, mainly stuff about how you did some things in a roundabout way or some nitpicky safety stuff.

<details>
<summary>Actual Issues</summary>

- Usage of the `[]` access modifiers when `.at()` is avaibale
- Despite warning the user when the file fails to open, there is no `exit()` or `abort()` or `throw ...` to exit the program
- `findCalibrationValueSum_v2` does not even do the file check, and doesn't even print the result

</details>

<details>
<summary> Nitpicks</summary>

- Some of your variables aren't super readable. I would advise moving them closer to the loops or even *inside* the loops (compilers nowadays are smart enough to optimize that).
- Using built-in initializers like `std::basic_ifstream(const char *__s)` or `std::vector(std::size_t __n, const std::allocator<int> &__a)` instead of relying on additional overhead like `<algotithm>`'s `std::fill()`
- Loops where you count `sum` are redundant
- Replacing `std::map` with `std::unordered_map` could net you a slight speed bonus, as the benefits of `std::map` are not needed

</details>

**Comment by jeffstevens98** [comment]
Hi! Thanks for looking at my code, mate! I appreciate it. I'm going to look at your research your suggestions and take a look at your pull request. Always trying to get better :)
